### ISSUE TITLE
Frequency unit misunderstanding?

### ISSUE THREAD

**Issue by sunnycase** [anjdreas/UnitsNet#256] opened 2017-05-27 09:59 UTC
1 CPM(CyclesPerMinute) should be equal to 1/60 Hertz.
But when using the Frequency struct, 1 CPM is equal to 60 Hertz.

reference:
http://www.kylesconverter.com/frequency/cycles-per-minute-to-hertz

**Comment by anjdreas** [comment] 2017-05-27 11:50
Thanks, that sounds like the conversion function has been inverted.
I did reproduce your results so it's clearly a bug, and from the git history it's been with us since August 2015 :-S I can only assume this particular unit has not been used much.

Nuget 3.63.0 with fix is now out.
Fixed in: cb7989843d3360a7b5df70fcc2821f199e9c4d62

**Closed by anjdreas** 2017-05-27 11:50 UTC
