### ISSUE TITLE
FeetInches always shows inches

### ISSUE THREAD

**Issue by MusicMonkey5555** [anjdreas/UnitsNet#158] opened 2016-04-11 19:36 UTC
When creating a FeetInches object if you pass it a whole value like 4ft it turns into 3ft 12 inch. It would be nice if there was an option to tell it how to handle this.

**Comment by anjdreas** [comment] 2016-04-20 20:57
Hi, sorry for the delay. Sounds like a rounding problem to me?
I ran the following in LinqPad on UnitsNet 3.33.0:
```
Length.FromFeet(4).FeetInches
// Feet	4
// Inches	7.1054273576010019E-15

Length.FromFeet(4).FeetInches.ToString() // 4 ft 0 in

new FeetInches(4, 0)
// Feet	4
// Inches	0

new FeetInches(4, 0).ToString() // 4 ft 0 in

```

So I can't reproduce, however I do see that there is a very small negative value on Inches, so without proper rounding it would give 3 ft 12 in. Can you paste me an example code that produces this error?

**Comment by anjdreas** [comment] 2016-08-02 21:02
Did that example make sense to you?

**Comment by anjdreas** [comment] 2016-10-21 21:46
Closing, will reopen if there are any further discussions.

**Closed by anjdreas** 2016-10-21 21:46 UTC
